-   name: Create AWS instance
    hosts: localhost
    connection: local
    gather_facts: False
    remote_user: ec2-user
    become: yes
    become_user: root
    vars_files: 
    - /etc/ansible/var_files/stackout.txt

    roles:
        - ec2-create
-   name: Install packages
    hosts: ec2_hosts
    remote_user: ec2-user
    roles:
    - nginx
