- name: Terminate instances
  hosts: localhost
  connection: local
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        ec2_region: us-west-2
        instance_ids: 'i-f913a56c'
